config/routes.rb
Rails.application.routes.draw do


  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:index]
  resources :moves
  get "/:player_id/moves", controller: :moves, action: :player_moves, as: :player_moves
  get "/:recipient_id/challenges", controller: :challenges, action: :personal_challenges, as: :personal_challenges
  resources :games do
    resources :leaderboards, :only => [:index, :show]
    resources :challenges
  end
  get "/wikipedia/*path", to: "wikipedia#show", :constraints => { :path => /.+/ }
  root "welcome#index"
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :challenges, dependent: :destroy
  has_many :moves, through: :players
  before_destroy :destroy_players_moves

  def winner?(player)

    if Move.where(player: player, :to_point => "https://en.wikipedia.org#{self.end_point}").present? == true
      "WON!"
    elsif Move.where(player: player, cheater: false).count > 0
      "Filthy Cheater"
    else
      "You did not Finish....weak"
    end
  end

  def create_start_wiki_path
    URI(self.start_point).path
  end

  def create_end_wiki_path
    URI(self.end_point).path
  end

  def set_start_point
    @start_point ||= WikiData.new.article_size_generate
  end

  def set_end_point
    @end_point ||= WikiData.new.article_size_generate
  end

  private

  def destroy_players_moves
    self.players.delete_all
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authorize!, except: [:index]

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    session[:game_id] = @game.id
    wiki_path = @game.create_start_wiki_path
    @player = Player.create(user_id: current_user.id, game_id: @game.id)

    session[:player_id] = @player.id
    redirect_to "/wikipedia#{wiki_path}"
  end

  def new
    @game = Game.new
  end

  def edit
  end

  def create
    @game = Game.create(
      start_point: WikiData.new.article_size_generate,
      end_point: WikiData.new.article_size_generate
    )

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game }
        format.json { render :show, status: :created, location: @game }
        flash[:success] = "Successfully Created a Game!"
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

private
  def game_params
    params.permit(:game).permit(:start_point, :end_point)
  end
end

app/helpers/games_helper.rb
module GamesHelper

  def name_url_cleanup(url_path)
    URI.decode(url_path.split('/')[-1].tr('_', ' ').to_s.gsub(" %26","\'s"))
  end

  def current_game_start_name
    name_url_cleanup(current_game.create_start_wiki_path)
  end

  def current_game_end_name
    name_url_cleanup(current_game.create_end_wiki_path)
  end

  def play_random_game_link
    if current_user
      link_to "Play Random Game", games_path, method: :post, class: "btn btn-lg btn-primary btn-block", data: {disable_with: "Creating Game..."}
    else
      link_to "Login to play", games_path, method: :post, class: "disabled btn btn-lg btn-primary btn-block", data: {disable_with: "Creating Game..."}
    end
  end

  def play_game_link(game)
    if current_user
      link_to 'Play', game, class: "btn btn-info wiggle-me"
    else
      link_to 'Login to play', game, class: "disabled btn btn-info"
    end
  end

  def column_with_method
    return "col_width_setting_disabled" unless current_user

    if current_user.admin?
      "col_width_setting_admin"
    else
      "col_width_setting"
    end
  end

  def play_custom_game_link
    #Create Custom Game
    if current_user
      link_to "Custom Game Feature Coming Soon", new_game_path, class: "disabled btn btn-lg btn-info btn-block"
    else
      link_to "Login to Create Custom Game", new_game_path, class: "disabled btn btn-lg btn-info btn-block"
    end
  end

end

app/views/games/_form.html.erb
<% @game.errors.full_messages.each do |message| %>
  <div class="alert alert-danger"><%= message %></div>
<% end %>

<%= form_for game do |f| %>

  <div class="form-group">
    <%= f.label :start_point %>
    <%= f.url_field :start_point, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :end_point %>
    <%= f.url_field :end_point, class: 'form-control' %>
  </div>

  <hr>

  <%= f.submit "Create Game", class: 'btn btn-primary', data: {disable_with: "Creating Game..."}  %>
<% end %>

app/views/games/edit.html.erb
<h1 class="text-center">Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Choose Game</h1>


<link href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
<div class="container">
  <div class="table-responsive">
    <table id="game_index" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Starting Article</th>
          <th>Ending Article</th>
          <th class="<%= "#{column_with_method}" %>">Options</th>
        </tr>
      </thead>

      <tbody>
        <% for game in @games %>
          <tr>
            <td><%= name_url_cleanup(game.start_point) %></td>
            <td><%= name_url_cleanup(game.end_point) %></td>
            <td class="button_spacing"><%= play_game_link(game) %>
            <% if current_user && current_user.admin? %>
              <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
              <%= link_to 'Show Leaderboard', game_leaderboards_path(game), class: "btn btn-primary" %>
              <%= send_challenge_link(game) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>

<br>
<%= play_random_game_link %>
<%= play_custom_game_link %>


<br>
<br>
<br>

app/views/games/new.html.erb
<h1 class="text-center">Create Custom Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<h1 class="text-center">Show Wiki Page
<small>
  <%= link_to 'Back', games_path %>
</small></h1>

<%= render 'showwikipage', game: @game %>

<div class="bg_load"></div>
<div class="wrapper">
    <div class="inner">
        <span>L</span>
        <span>o</span>
        <span>a</span>
        <span>d</span>
        <span>i</span>
        <span>n</span>
        <span>g</span>
    </div>
</div>