config/routes.rb
Rails.application.routes.draw do


  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:index]
  resources :moves
  get "/:player_id/moves", controller: :moves, action: :player_moves, as: :player_moves
  get "/:recipient_id/challenges", controller: :challenges, action: :personal_challenges, as: :personal_challenges
  resources :games do
    resources :leaderboards, :only => [:index, :show]
    resources :challenges
  end
  get "/wikipedia/*path", to: "wikipedia#show", :constraints => { :path => /.+/ }
  root "welcome#index"
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  has_one :user, through: :player
  has_many :players, through: :game
  belongs_to :game

  def recipient_status_known(email)
    if User.exists?(email: email)
      a = User.find_by(email: email)
      self.update_attribute :recipient_id, a.id
    end
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authorize!
  def new
    @game = Game.find_by id: params[:game_id]
    @challenge = Challenge.new(game_id: @game)
  end

  def create
    @challenge = Challenge.create(challenge_params)
    flash[:success] = "You successfully sent a Challenge!"

    if @challenge.save
      @challenge.recipient_status_known(@challenge.recipient_email)
      ChallengeMailer.send_challenge(@challenge).deliver_now
      redirect_to games_path
    else
      render :new, notice: 'Email Exists'
    end
  end

  def personal_challenges
    @recipient = Challenge.find_by recipient_id: params[:recipient_id]
  end


  private

  def challenge_params
    params.require(:challenge).permit(:game_id, :challenger_id, :recipient_id, :recipient_email, :recipient_name)
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
  def send_challenge_link(game)
    if current_user
      link_to 'Challenge a Friend',  new_game_challenge_path(game), class: "btn btn-warning"
    else
      link_to 'Login to send Challenge',  new_game_challenge_path(game), class: " disabled btn btn-warning"
    end
  end
end

app/views/challenges/_form.html.erb
<%= form_for challenge, url: game_challenges_path(@game) do |f| %>

  <div class="form-group">
  <%= f.label :recipient_name %>
  <%= f.text_field :recipient_name, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :recipient_email %>
  <%= f.text_field :recipient_email, class: 'form-control' %>
  </div>


  <div class="form-group">
  <%= f.hidden_field :challenger_id, :value => current_user.id, :class => "form-control"%>
  </div>
  <div class="form-group">
  <%= f.hidden_field :game_id, :value => @game.id, :class => "form-control"%>
  </div>

  <%= f.submit "Send Challenge", class:"btn btn-default" %>
<% end %>

app/views/challenges/create.html.erb
<h1>Challenges#create</h1>
<p>Find me in app/views/challenges/create.html.erb</p>

app/views/challenges/new.html.erb
<h1 class="text-center">New Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Back', games_path %>

app/views/challenges/personal_challenges.html.erb
<h2>Challenges Recieved</h2>

<link href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
<div class="container">
<table id="game_index" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Challenge Counter</th>
      <th>From</th>
      <th>To</th>
      <th>Challenge From</th>
      <th>Start Challenge</th>
    </tr>
  </thead>
  <tbody>
    <% index = 0 %>

    <% Challenge.where(recipient_id: @recipient.recipient_id).find_each do |challenge| %>
      <tr>
        <td><%= index += 1 %></td>
        <td><%= name_url_cleanup(challenge.game.start_point) %></td>
        <td><%= name_url_cleanup(challenge.game.end_point) %></td>
        <td><%= User.find_by(id: challenge.challenger_id).full_name %></td>
        <td class="button_spacing"><%= link_to 'Play', challenge.game, class: "btn btn-info" %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>

<h2>Challenges Sent</h2>

<div class="container">
<table id="game_index" class="table table-striped table-bordered" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Challenge Counter</th>
      <th>From</th>
      <th>To</th>
      <th>Challenge to</th>
      <th>Start Challenge</th>
    </tr>
  </thead>
  <tbody>
    <% index = 0 %>

    <% Challenge.where(challenger_id: current_user.id).find_each do |challenge| %>
      <tr>
        <td><%= index += 1 %></td>
        <td><%= name_url_cleanup(challenge.game.start_point) %></td>
        <td><%= name_url_cleanup(challenge.game.end_point) %></td>
        <td><%= challenge.recipient_name %></td>
        <td class="button_spacing"><%= link_to 'Play', challenge.game, class: "btn btn-info" %>
      </tr>
    <% end %>
  </tbody>
</table>