config/routes.rb
Rails.application.routes.draw do


  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:index]
  resources :moves
  get "/:player_id/moves", controller: :moves, action: :player_moves, as: :player_moves
  get "/:recipient_id/challenges", controller: :challenges, action: :personal_challenges, as: :personal_challenges
  resources :games do
    resources :leaderboards, :only => [:index, :show]
    resources :challenges
  end
  get "/wikipedia/*path", to: "wikipedia#show", :constraints => { :path => /.+/ }
  root "welcome#index"
end

app/controllers/wikipedia_controller.rb
class WikipediaController < ApplicationController
  def show
    @wiki_parser = WikiData.new
    @link_path = @wiki_parser.expand_wikipedia_article(params["path"])

    @from_path = @wiki_parser.save_previous_url(request)

    @page_to_render = @wiki_parser.get_page(@link_path)

    @not_cheating = @wiki_parser.cheating_test(@from_path, params['path'])
    Move.find_or_create_by(player_id: current_player.id, to_point: @link_path, from_point: @from_path, cheater: @not_cheating)

    if @wiki_parser.params_path_formatter(params["path"]) == @wiki_parser.params_path_formatter(current_game.create_end_wiki_path)
      @won = true
      @won
    end
  end
end

app/helpers/wikipedia_helper.rb
module WikipediaHelper

end

app/views/wikipedia/_americanflag.html.erb
<!-- Got it from Here -"http://phrogz.net/tmp/canvas_flag_wave2.html" - -->
<style type="text/css" media="screen">
	body { background:#eee }
	#flag { position:absolute; left:50% }
</style>
<script type="text/javascript">
window.onload = function(){
	var flag = document.getElementById('flag');
	drawAmericanFlag( flag, 320, 0, 40 );
	flag.style.marginLeft = -(flag.width/2)+'px';
	flag.style.marginTop  = -(flag.height/2)+'px';
	var timer = waveFlag( flag, 20, 10, 150, 200, -0.1 );
};

function drawAmericanFlag( canvas, width, padX, padY ){
	if (!padX) padX = 0;
	if (!padY) padY = 0;
	// http://www.montney.com/flag/proportions.htm
	var a = width / 1.9;
	var b = width;
	var c = 7*a/13;
	var d = 0.76*a;
	var e = 0.054*a;
	var g = 0.063*a;
	var k = 0.0616*a;
	var l = a / 13;
	canvas.width  = b+2*padX;
	canvas.height = a+2*padY;
	var ctx = canvas.getContext('2d');

	// Stripes
	ctx.fillStyle = '#fff';
	ctx.fillRect(padX,padY,b,a);
	ctx.fillStyle = '#900';
	for (var i=0;i<13;i+=2) ctx.fillRect(padX,i*l+padY,b,l);

	// Field
	ctx.fillStyle = '#009';
	ctx.fillRect(padX,padY,d,c);

	// Stars
	ctx.fillStyle = '#fff';
	for (var row=1;row<=9;++row){
		for (var col=1;col<=11;++col){
			if ((row%2==1 && col%2==0) || (row%2==0 && col%2==1)) continue;
			ctx.beginPath();
			ctx.arc(col*g+padX,row*e+padY,k/3,0,Math.PI*2,false);
			ctx.closePath();
			ctx.fill();
		}
	}

	// Border
	ctx.strokeStyle = 'rgba(0,0,0,0.5)';
	ctx.lineWidth = 1;
	ctx.strokeRect( padX, padY, b, a );
}

function waveFlag( canvas, wavelength, amplitude, period, shading, squeeze ){
	if (!squeeze)    squeeze    = 0;
	if (!shading)    shading    = 100;
	if (!period)     period     = 200;
	if (!amplitude)  amplitude  = 10;
	if (!wavelength) wavelength = canvas.width/10;

	var fps = 30;
	var ctx = canvas.getContext('2d');
	var   w = canvas.width, h = canvas.height;
	var  od = ctx.getImageData(0,0,w,h).data;
	// var ct = 0, st=new Date;
	return setInterval(function(){
		var id = ctx.getImageData(0,0,w,h);
		var  d = id.data;
		var now = (new Date)/period;
		for (var y=0;y<h;++y){
			var lastO=0,shade=0;
			var sq = (y-h/2)*squeeze;
			for (var x=0;x<w;++x){
				var px  = (y*w + x)*4;
				var pct = x/w;
				var o   = Math.sin(x/wavelength-now)*amplitude*pct;
				var y2  = y + (o+sq*pct)<<0;
				var opx = (y2*w + x)*4;
				shade = (o-lastO)*shading;
				d[px  ] = od[opx  ]+shade;
				d[px+1] = od[opx+1]+shade;
				d[px+2] = od[opx+2]+shade;
				d[px+3] = od[opx+3];
				lastO = o;
			}
		}
		ctx.putImageData(id,0,0);
		// if ((++ct)%100 == 0) console.log( 1000 * ct / (new Date - st));
	},1000/fps);
}

</script>
</head><body>
<canvas id="flag"></canvas>
</body>

app/views/wikipedia/_cheating.html.erb
<h2>YOU CHEATED!!!! YOU CHEATED!!!! YOU CHEATED!!!! YOU CHEATED!!!! </h2>
<h3><%= link_to "Go Back to Main Page you CHEATER", games_path %></h3>

app/views/wikipedia/_imageinfo.html.erb
<%= link_to image_tag('info.png'), "https://en.wikipedia.org#{url_location}", :class=> "info_hover", :target => "_blank" %>
<span class="text_hover_img">Click here wont affect the number of moves.</span>

app/views/wikipedia/_showwikipage.html.erb
<% if @won == true %>
  <%= link_to "Look at The Path You Took", player_moves_path(current_player), class: "btn btn-lg btn-primary btn-block" %>
  <hr>
  <br>
  <br>
  <br>
  <br>
  <%= render 'americanflag'%>

  <br>
  <br>
  <br>


<% elsif render_cheater == true %>
  <hr>
  <%= render 'cheating'%>
<% else %>
  <div class="wikipedia">
    <span class="square individual">
      <%= @page_to_render.to_s.html_safe %>
    </span>
  </div>

<% end %>

app/views/wikipedia/show.html.erb
<h1 class="text-center">
  <% if @won == true %>
    YOU WON!!!!
  <% elsif render_cheater == true%>
    YOU CHEATED!!!!
  <% else %>
    <%= game_move_count_funny_message %>
  <% end %>
</h1>

<div class="wikipedia_container_header">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <h4>Starting Point:  <%= current_game_start_name %>
          <%= render 'imageinfo', url_location: current_game.start_point %>
          <% if game_move_count <= 1 %>
            <div class = "icon_text_first_move">
              <%= "<-- Click Icon to view this Wikipedia Page on another tab (won't count as a move)" %>
            </div>
          <% end %>
          <br>
          <span class="end_display"> Ending Point: <%= current_game_end_name %>
            <%= render 'imageinfo', url_location: current_game.end_point %>
            <% if game_move_count <= 1 %>
            <div class = "icon_text_first_move">
              <%= "<-- Click Icon to view this Wikipedia Page on another tab (won't count as a move)" %>
            </div>
            <% end %>
          </span>
        </h4>
      </div>
        <div class="col-md-3">
          <span class="pull-right">
          <h4>  Current Number of Moves: <%= game_move_count %>
            <br>
            Game Timer: <%= gametimer(current_game)%></h4>
          </span>
        </div>
      </div>
  </div>
</div>
<%= render 'showwikipage', game: @game %>