config/routes.rb
Rails.application.routes.draw do


  resource :session, only: [:new, :create, :destroy]
  resources :users, except: [:index]
  resources :moves
  get "/:player_id/moves", controller: :moves, action: :player_moves, as: :player_moves
  get "/:recipient_id/challenges", controller: :challenges, action: :personal_challenges, as: :personal_challenges
  resources :games do
    resources :leaderboards, :only => [:index, :show]
    resources :challenges
  end
  get "/wikipedia/*path", to: "wikipedia#show", :constraints => { :path => /.+/ }
  root "welcome#index"
end

app/views/layouts/application.html.erb
<html>
<style type="text/css">
/*This causes the cheater link to fail*/
/*body {
  background: url('<%= randomized_background_image %>') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}*/
</style>
  <head>
    <title>Wikipedia Game</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
           <%= link_to image_tag('fun_wiki_logo.png', size: '50x50', class: "info_hover"), root_path, class: "navbar-brand", id:"logo" %>
        </div>
        <div class="collapse navbar-collapse" id="wikipedia-nav">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "games", games_path %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Signed in as <%= current_user.full_name %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Scoreboard", user_path(current_user.id) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "My Challenges", personal_challenges_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Log out", session_path, method: :delete %></li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Log In", new_session_path %></li>
              <li><%= link_to "Sign Up!", new_user_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>


<link href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
    <div class="container">
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %>">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>


  </body>
</html>